# Generated by Django 2.2.5 on 2019-10-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_auto_20191010_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='star',
            new_name='start',
        ),
    ]
